service: attendance-api

custom:
  env: ${lower(${opt:stage, self:provider.stage})}
  layerName: ${self:service}-dependencies-${self:custom.env}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    current: ${self:custom.vpcSettings.${self:custom.env}, ''}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}
    NODE_OPTIONS: '--enable-source-maps'

layers:
  dependencies:
    name: ${self:custom.layerName}
    description: Dependencies layer for ${self:service}
    compatibleRuntimes:
      - nodejs20.x
    licenseInfo: MIT
    path: layer
    package:
      artifact: layer.zip
    retain: false

functions:
  api:
    handler: lambda.universal
    layers:
      - { Ref: DependenciesLambdaLayer }
    events:
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    vpc: ${self:custom.vpcSettings.current, ''}
    package:
      patterns:
        - '!node_modules/**'
        - '!layer/**'
        - '!layer.zip'

plugins:
  - serverless-plugin-utils
